### ISSUE TITLE
文章打开速度比leanote仓库的版本慢很多

### ISSUE THREAD

**Issue by wg1026688210** [ctaoist/leanote-theme-chirpy#2]
是否服务端和客户端会下载其他网站的静态文件

**Comment by ctaoist** [comment]
哪两种情况的对比？展开说说？服务端版本，哪个主题这些。
给个线索：这个主题引用了很多 jsdeliver CDN 的文件。

**Comment by wg1026688210** [comment]
之前服务端和版本都是用的leanote repo的，现在用的咱们的2.7版本的server，和这个最新的主题
大致明白了，
请教下，CDN文件能不能优化成本地文件

**Comment by wg1026688210** [comment]
可以加个配置，比如说部署在国内服务器，带宽充足的用户可以配置加载本地文件，带宽不充足的用户可以配置cdn

**Comment by ctaoist** [comment]
你在哪个地方，居然 jsdelivr 都会慢，而且有缓存，只用取一次，过期时间要很久。

有这个计划，但优先级比较低。最近在把渲染引擎修改成 markdown-it。

**Comment by wg1026688210** [comment]
我这边是北京，在家用F12发现确实有几个下载时间相对较长的静态文件，用手机会更慢一些，主要是担心查看我博客的新用户等待时间较长放弃看我的文章。你先按你的节奏来，去掉cdn做好了通知我试用下就行。

**Comment by ctaoist** [comment]
每次都是那几个文件还是随机的几个文件要等很久，
如果不是随机的哪些文件啊

**Comment by wg1026688210** [comment]
![image](https://user-images.githubusercontent.com/14267759/148744854-974e491e-aa9b-41c3-bba5-a0c6b25a41d3.png)
![image](https://user-images.githubusercontent.com/14267759/148745012-eb28c195-3a1c-4c4c-bb55-6fa8616f825b.png)

**Comment by ctaoist** [comment]
这几个文件确实引用的CDN，我找时间增加切换cdn的功能

**Comment by wg1026688210** [comment]
太感谢了

**Comment by ctaoist** [comment]
你试试吧，已经更新了 @wg1026688210 
服务端要2.7.2

**Comment by wg1026688210** [comment]
感谢，我最近找时间试下再反馈给你

**Comment by wg1026688210** [comment]
![image](https://user-images.githubusercontent.com/14267759/149745044-96101dd1-5a62-472f-b7bc-a3ce5d527bd7.png)
我这边zip -r master分支，上传会有问题
是不是我打包静态文件方式有问题

**Comment by ctaoist** [comment]
之前能成功吗，你看看终端有没有啥输出，你服务端是不是用的还是2.6的啊

**Comment by wg1026688210** [comment]
可以了，我的theme.json写的有问题, 相应速度确实比以前快了很多

**Comment by ctaoist** [comment]
我也是才发现，也是从最近两天开始的，jsdelivr的速度确实慢很多了，国内的备案被撤销了
