### ISSUE TITLE
2.6分支的一个css资源失效

### ISSUE THREAD

**Issue by jqtmviyu** [ctaoist/leanote-theme-chirpy#4]
//cdn.jsdelivr.net/gh/ctaoist/leanote@cdev/public/js/google-code-prettify/prettify.min.css  

需要替换为 https://cdn.jsdelivr.net/gh/ctaoist/leanote@2.7.2/public/libs/google-code-prettify/prettify.min.css

ps: 1. login页面的体验按钮没有屏蔽, 有没有可能被人乱塞数据库塞爆
2. 
![image](https://user-images.githubusercontent.com/19925192/161384349-dddbcec2-bfe5-4204-9bba-b9b05cf06af2.png)
请问你部署后这个退出登录接口也是失效了吗?

**Comment by ctaoist** [comment]
静态资源链接已经修复了。
退出按钮的功能是正常的啊，你的后台管理里面的site_url是不是没设置好

**Comment by jqtmviyu** [comment]
> 静态资源链接已经修复了。 退出按钮的功能是正常的啊，你的后台管理里面的site_url是不是没设置好

应该是我设置问题. 

https://blog.ctaoist.cn/demo    暴露了出来, 且里面的数据不会定时清空. 我似乎也没找到删除测试账号的方法

**Comment by ctaoist** [comment]
是暴露出来了，我找时间看看吧，最近在搞别的事情

**Comment by ctaoist** [comment]
> https://blog.ctaoist.cn/demo 暴露了出来, 且里面的数据不会定时清空. 我似乎也没找到删除测试账号的方法

暂时先在 nginx 中禁掉 `/demo` 路径了：

```
server { 
    # 省略部分
    location /demo {
        deny all;
    }
}
```

暂时先这么处理吧。
