### ISSUE TITLE
ategories标签点击没有跳转

### ISSUE THREAD

**Issue by buleshit** [ctaoist/leanote-theme-chirpy#7]
加载主题发现2个问题：
1、home页面只显示1篇文章
2、categories标签点击没有跳转

![image](https://user-images.githubusercontent.com/7974216/204230923-87720e10-9cb0-4fc3-961f-f0fe70f53325.png)

**Comment by buleshit** [comment]
可能是使用了官方的服务端的原因，更新一下试试后再回来

**Comment by buleshit** [comment]
使用了修改的服务端2.7.7版本，主页只显示一篇的问题解决了。
但是分类页没有目录的问题还存在。
分类应该只需要在笔记中将目录公开为博客就行了吧？还有其他设置吗？

**Comment by ctaoist** [comment]
我修改后的版本是不用把整个目录公开为博客才对的啊，不仅后端要用修改后的，主题前端还是要用master分支，估计你前端主题还是没有切换过来

![image](https://user-images.githubusercontent.com/14012127/205558753-843b9a9b-5d71-4b67-9016-837369ab2db2.png)

**Comment by buleshit** [comment]
> 
分类的问题解决了，这里应该是有一个bug：
更新leanote和主题版本之前创建的博文，不会在分类中显示。新建的博文可以正常显示。

**Comment by ctaoist** [comment]
wiki中已经有说明了：
https://github.com/ctaoist/leanote/wiki/Leanote-install#%E4%BB%8E-26-%E5%8D%87%E7%BA%A7
